# Generated by Django 2.2.16 on 2023-01-31 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0006_auto_20230130_2117"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name="ID")),
                ("text",
                 models.TextField(help_text="Оставьте свой комментарий")),
                ("created", models.DateTimeField(auto_now_add=True,
                                                 verbose_name="Дата комментария")),
                ("author",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="comment",
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name="Автор")),
                ("post",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="comment", to="posts.Post",
                                   verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ["-created"],
            },
        ),
    ]
