# Generated by Django 2.2.16 on 2023-02-02 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0007_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment", to="posts.Post"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(help_text="Оставьте свой комментарий",
                                   verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, upload_to="posts/",
                                    verbose_name="Добоавьте картинку"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pub_date",
            field=models.DateTimeField(auto_now_add=True, db_index=True,
                                       verbose_name="Дата публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(help_text="Введите текст публикации",
                                   verbose_name="Текст поста"),
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name="ID")),
                ("author",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="following",
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name="Автор")),
                ("user",
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name="follower",
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name="Подписчик")),
            ],
        ),
    ]
